### ISSUE TITLE
Getting any luck with USART3

### ISSUE THREAD

**Issue by jlatas** [MX-Master/STM32H7_Nucleo-H743ZI_Ethernet_LwIP#2]
Do you mind to provide a USART3 working?

I have been trying to develop it, but without any luck, tried several ways, with cubeMX examples and stm32 examples. I checked the registers everything seems ok, it transmits but the data transmitted is corrupted.

Checked several times the baud rate from the terminal and from the code everything seems ok.

It looks like there is something not working with the nucleo 144 clock.

Thank you in advance.

**Comment by jlatas** [comment]
If the USART3 uses the HSI as a clock source it works, therefore it looks like some conflict in the use of _D2PCLK1

**Comment by MX-Master** [comment]
A few days ago I made a clock fix for the code - https://github.com/MX-Master/STM32H7_Nucleo-H743ZI_Ethernet_LwIP/commit/54b5feae9792621a348c655a90d96bb472a08b72

I think it will help to solve your problem (:

**Comment by jlatas** [comment]
Thank you! I was using the previous version before that fix.
Really helpful.
